[theme]

# Primary accent color for interactive elements.
primaryColor = "#3b4856"

# Background color for the main content area.
backgroundColor = "#F6F9F5"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F6F9F5"

# Color used for almost all text.
textColor = "#0c2321"
